config/routes.rb
PromoFinder::Application.routes.draw do
  resources :catalogos

  
	
	  resources :produtos do 
  	  collection do
  	    get :search
  	  
      end
    end

   root :to => 'produtos#search'

   match ':controller(/:action(/:id))(.:format)'

end

app/controllers/application_controller.rb
# encoding: utf-8
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  # GET /produtos
  # GET /produtos.json
  def index
    @produtos = Produto.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @produtos }
    end
  end

  
  def search
 
   respond_to do |format|
      format.html # show.html.erb
	end
  end
  
  
  def buscar
 
   @produto = Produto.where("codigo_barras = ?", params[:search])
	id = "notFound"
	data = Time.new.to_date
	@produto.each do |prod|
		if (prod.catalogo.data_inicio <= data and prod.catalogo.data_fim >= data)
			id = prod.id.to_s
		end
	end	
   respond_to do |format|
      format.html { redirect_to ("/produtos/" + id)}
      format.json { render :json => @produto }
	end
  end
  
  # GET /produtos/1
  # GET /produtos/1.json
  def show
  begin
		@produto = Produto.find(params[:id])
	rescue
		@produto = nil
	end
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @produto }
    end
  end

  # GET /produtos/new
  # GET /produtos/new.json
  def new
    @produto = Produto.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @produto }
    end
  end

  # GET /produtos/1/edit
  def edit
    @produto = Produto.find(params[:id])
  end

  # POST /produtos
  # POST /produtos.json
  def create
    @produto = Produto.new(params[:produto])
	  @catalogo = Catalogo.find(params[:catalogo][:id])
	  @produto.catalogo = @catalogo
    respond_to do |format|
      if @produto.save
        format.html { redirect_to "/produtos/new", :notice => 'Produto adicionado com sucesso' }
        format.json { render :json => @produto, :status => :created, :location => @produto }
      else
        format.html { render :action => "new" }
        format.json { render :json => @produto.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /produtos/1
  # PUT /produtos/1.json
  def update
    @produto = Produto.find(params[:id])
	@catalogo = Catalogo.find(params[:catalogo][:id])
	@produto.catalogo = @catalogo
    respond_to do |format|
      if @produto.update_attributes(params[:produto])
        format.html { redirect_to produtos_url, :notice => 'Produto alterado com sucesso' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @produto.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1
  # DELETE /produtos/1.json
  def destroy
    @produto = Produto.find(params[:id])
    @produto.destroy

    respond_to do |format|
      format.html { redirect_to produtos_url }
      format.json { head :no_content }
    end
  end
  

  def destroy_produto
    @produto = Produto.find(params[:id])
    @produto.destroy
	url = "/produtos"
	if params[:catalogo_id] != nil
		url = "/catalogos/" + params[:catalogo_id].to_s
	end
	
	 respond_to do |format|
		format.html { redirect_to url, :notice => 'Produto removido com sucesso' }
      format.json { head :no_content }
    end
	
  end
  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/catalogos_helper.rb
module CatalogosHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/catalogos/_form.html.erb
<script>
function onEnterLogin() {
 var keyCode = event.keyCode ? event.keyCode : event.which ? event.which : event.charCode;
    if( keyCode == 13 ) {


        if(!e) var e = window.event;

        e.cancelBubble = true;
        e.returnValue = false;

        if (e.stopPropagation) {
                e.stopPropagation();
                e.preventDefault();
        }
}
	   
 }

 $(document).ready(function(){
	
$( "#catalogo_data_inicio" ).datepicker({
               regional: "pt-BR"
 });
 $( "#catalogo_data_fim" ).datepicker({
               regional: "pt-BR"
 });
 });
 
 function checkData(){
  var camposNaoPreenchidos = false;
  var dataErrada = false;
  var DateToValue = $("#catalogo_data_fim").val();
  var DateFromValue = $("#catalogo_data_inicio").val();

  
   var parts = DateToValue.split("/");
   var date_inicio = new Date(parts[1] + "/" + parts[0] + "/" + parts[2]);

   parts = DateFromValue.split("/");
   var date_final = new Date(parts[1] + "/" + parts[0] + "/" + parts[2]);

  if ((date_inicio.getTime()) < (date_final.getTime())) {
		alert("Data final deve ser maior que a inicial!");
		dataErrada = true;
	}	
	
  if($("#catalogo_nome").val().length === 0 || $("#catalogo_data_inicio").val().length === 0 || $("#catalogo_data_fim").val().length === 0) {
  		alert("Por favor preencha os campos indicados por *.");
		camposNaoPreenchidos = true;

  }
	
	if(dataErrada || camposNaoPreenchidos){
		var e = window.event;
		e.cancelBubble = true;
		e.returnValue = false;

		if (e.stopPropagation) {
            e.stopPropagation();
            e.preventDefault();
			}
		}
}
 
 
</script>

<style>
th {
	height: 0px;
}
</style>
<%= stylesheet_link_tag "jqueryui.css" %>


<%= form_for(@catalogo) do |f| %>
  <% if @catalogo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@catalogo.errors.count, "erro") %> impediram o catálogo de ser salvo:</h2>

      <ul>
      <% @catalogo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <label><%=  "Marca"  %><span class="asterisk" >*</span>:</label> 
		<%= f.select :marca, ([["Avon", "Avon"], ["Jequiti", "Jequiti"], ["Natura", "Natura"]]) %>
  </p>
  
   <p>
    <label><%=  "Nome"  %><span class="asterisk" >*</span>:</label> 
    <%= f.text_field :nome, :onkeypress => "onEnterLogin()" %>
 </p>
   <p>
    <label><%=  "Data Início"  %><span class="asterisk" >*</span>:</label> 
    <%= f.text_field :data_inicio, :size => "10" %>
  </p>
   <p>
    <label><%=  "Data Fim"  %><span class="asterisk" >*</span>:</label> 
    <%= f.text_field :data_fim, :size => "10" %>
</p>
  <div class="actions">
     <%= submit_tag "Salvar", :class => "button negative", :onclick => "checkData();" %> 

  </div>
<% end %>

app/views/catalogos/index.html.erb
<div class="title"><span class="title_icon"><img src="/assets/bullet1.gif" alt="" title="" /></span>Catálogos</div>
<script>
$(document).ready(function(){
	$('#menu_buscarProduto').removeClass('selected');
	$('#menu_newProduto').removeClass('selected');
	$('#menu_produtos').removeClass('selected');
	$('#menu_newRevista').removeClass('selected');
	$('#menu_revistas').removeClass('selected');
	$('#menu_revistas').addClass('selected');

 });
 
  function confirmaDelete(){
	if(!confirm("Deseja remover esse catálogo?")){
		var e = window.event;
		e.cancelBubble = true;
		e.returnValue = false;

		if (e.stopPropagation) {
            e.stopPropagation();
            e.preventDefault();
			}
		}
	}

</script>
<div style="margin-left: 49px;color:green;font-family: calibri;font-size:12pt;">
<% flash.each do |name, msg| %>
   <b>   <%= content_tag :div, msg, :id => "flash_#{name}" %> </b>
	  <% end %>
</div>

<div style="margin-left: auto; margin-right:auto;">   
<br/>
<br/>
<br/>
<br/>
<div align="right"> 
<%= link_to 'Adicionar Catálogo', new_catalogo_path, :style => "width:150px;", :class => " adicionar big negative button" %>

    </div>

<table align="center">

  <tr>
     <th style="width:150px">Marca</th>
    <th style="width:150px">Nome</th>
    <th style="width:150px">Data início</th>
    <th style="width:150px">Data fim</th>
    <th style="width:150px">Ações</th>
    
  </tr>

<% @catalogos.each do |catalogo| %>
  <tr>
    <td><%= catalogo.marca %></td>
    <td><%= catalogo.nome %></td>
    <td><%= catalogo.data_inicio.strftime("%d/%m/%Y") %></td>
    <td><%= catalogo.data_fim.strftime("%d/%m/%Y") %></td>
    <td>
	<%= link_to (image_tag "buttons/button_remove.png", :size => "20x20", :style => "margin-right:10px;" ) ,{:controller => 'catalogos', :action => 'destroy_catalogo', :id => catalogo.id},  :onclick => "confirmaDelete();"%>
	<%= link_to (image_tag "buttons/button_edit.png", :size => "20x20", :style => "margin-right:10px;" ) ,{:controller => 'catalogos', :action => 'edit', :id => catalogo.id}%>
	<%= link_to (image_tag "buttons/glass.png",:size => "20x20" ) ,{:controller => 'catalogos',:action => 'show', :id => catalogo.id}%>
  </tr>
<% end %>
</table>

<br />


</div>

app/views/catalogos/show.html.erb
<script>
$(document).ready(function(){
	$('#menu_buscarProduto').removeClass('selected');
	$('#menu_newProduto').removeClass('selected');
	$('#menu_produtos').removeClass('selected');
	$('#menu_newRevista').removeClass('selected');
	$('#menu_revistas').removeClass('selected');
	$('#menu_revistas').addClass('selected');

 });

 
  function confirmaDelete(){
	if(!confirm("Deseja remover esse produto?")){
		var e = window.event;
		e.cancelBubble = true;
		e.returnValue = false;

		if (e.stopPropagation) {
            e.stopPropagation();
            e.preventDefault();
			}
		}
	}
 
 
</script>
<div class="grid_16">
    	<h1>
    	   <div class="title"><span class="title_icon"><img src="/assets/bullet1.gif" alt="" title="" /></span>Detalhes Catálogo</div>
    	</h1>
	
	<div style="margin-left: 49px;color:green;font-family: calibri;font-size:12pt;">
		<% flash.each do |name, msg| %>
			<b>   <%= content_tag :div, msg, :id => "flash_#{name}" %> </b>
		<% end %>
	</div>

    	<div class="clear"></div>

    	<p></p>


		
    	<div class="formdiv">
     

	<br/>
	
	
  	
		<fieldset class="login" style="width: 350px;margin-right: auto;margin-left: auto;">
                <legend>Catálogo</legend>

	 <p>
	
    <label><%=  "Marca"  %>:</label> 
 	<label style="text-align: left;margin-left: 10px;"><%= @catalogo.marca %> </label> 
	</p>
	<p>
	
	 <p>
	
    <label><%=  "Nome"  %>:</label> 
 	<label style="text-align: left;margin-left: 10px;"><%= @catalogo.nome %> </label> 
	</p>
	<p>

    <label><%=  "Data início"  %>:</label> 
 	<label style="text-align: left;margin-left: 10px;"> <%= @catalogo.data_inicio.strftime("%d/%m/%Y") %></label> 
	</p>
	<p>
	
	 <label><%=  "Data Fim"  %>:</label> 
 	<label style="text-align: left;margin-left: 10px;"><%= @catalogo.data_fim.strftime("%d/%m/%Y") %> </label> 
	</p>
	</fieldset>
	
 
  <br/>

                <div>
    			</div>
         
    	</div>
    </div>

<table align="center">
  <tr>
    <th style="width:150px">Código</th>
    <th style="width:150px">Preço Promocional</th>
    <th style="width:150px">Preço Nominal</th>
	<th style="width:150px"> Ações </th>
  </tr>

  
<% @produtos.each do |produto| %>
  <tr>
	<td> <%= produto.codigo_barras %> </td>
	<td><%= (number_to_currency(produto.preco_promocional, :unit => "R$ ", :precision => 2, :separator => ",", :delimiter => ".")) %> </td>
	<td> <%= (number_to_currency(produto.preco_nominal, :unit => "R$ ", :precision => 2, :separator => ",", :delimiter => ".")) %></td>


    <td> 
	<%= link_to (image_tag "buttons/button_remove.png", :size => "20x20", :style => "margin-right:10px;" ) ,{:controller => 'produtos', :action => 'destroy_produto', :id => produto.id,  :catalogo_id => @catalogo.id}, :onclick => "confirmaDelete();"%>
	<%= link_to (image_tag "buttons/button_edit.png", :size => "20x20", :style => "margin-right:10px;" ) ,{:controller => 'produtos', :action => 'edit', :id => produto.id}%>
	<%= link_to (image_tag "buttons/glass.png",:size => "20x20" ) ,{:controller => 'produtos',:action => 'show', :id => produto.id}%>

  </tr>
<% end %>
</table>

<br />

app/views/produtos/_form.html.erb
<script>
function onEnterLogin() {
 var keyCode = event.keyCode ? event.keyCode : event.which ? event.which : event.charCode;
    if( keyCode == 13 ) {


        if(!e) var e = window.event;

        e.cancelBubble = true;
        e.returnValue = false;

        if (e.stopPropagation) {
                e.stopPropagation();
                e.preventDefault();
        }
	}
	   
 }
function checkPreco (){

	var camposNaoPreenchidos = false;
	var precoErrado = false;
	var precoNominal = $("#produto_preco_nominal").val().replace("R$", "").replace(",", ".");
	var precoPromocional = $("#produto_preco_promocional").val().replace("R$", "").replace(",", ".");;
	
	if(precoNominal < precoPromocional){
		alert("Preço Promocional deve ser menor que o nominal!");
		precoErrado = true;
	}
	
  if($("#produto_codigo_barras").val().length === 0 || $("#produto_preco_nominal").val().length === 0 || $("#produto_preco_promocional").val().length === 0) {
  		alert("Por favor preencha os campos indicados por *.");
		camposNaoPreenchidos = true;

  }

	if(precoErrado || camposNaoPreenchidos){
		var e = window.event;
		e.cancelBubble = true;
		e.returnValue = false;

		if (e.stopPropagation) {
            e.stopPropagation();
            e.preventDefault();
			}
		}
		
	else {
		$("#produto_preco_nominal").val(precoNominal);
		$("#produto_preco_promocional").val(precoPromocional)
	}	
}

 $(document).ready(function(){
 $("#produto_preco_nominal").priceFormat({
    prefix: 'R$ ',
    centsSeparator: ','
});


$("#produto_preco_promocional").priceFormat({
    prefix: 'R$ ',
    centsSeparator: ','
});


	if( $("#produto_preco_nominal").val().length === 0 ){
		$("#produto_preco_nominal").val("R$ 0,00");
	} 
	else {
			$("#produto_preco_nominal").val($("#produto_preco_nominal").val().replace(".", ","));

	}
	if( $("#produto_preco_promocional").val().length === 0){
		$("#produto_preco_promocional").val("R$ 0,00");
	} 
		else {
			$("#produto_preco_promocional").val($("#produto_preco_promocional").val().replace(".", ","));

	}

 });
 
</script>


<%= form_for(@produto) do |f| %>
  <% if @produto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@produto.errors.count, "error") %></h2>

      <ul>
      <% @produto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	<br/>
	<div style="margin-left: 152px;float: left;margin-top: -18px;margin-bottom: 6px;"> <img src="/assets/codigo.png" /></div>
  <p>
	
    	<label>Código<span class="asterisk" >*</span>:</label> 
 	<%= f.text_field :codigo_barras, :class => 'long_text' , :onkeypress => "onEnterLogin()" %> 
	</p>
	
	
   <p>
	
    	<label>Preço Nominal<span class="asterisk" >*</span>:</label> 
 	<%= f.text_field :preco_nominal, :class => 'long_text preco', :size => 10, :onkeypress => "onEnterLogin()"  %> 
	</p>
  
  	
   <p>
	
    	<label>Preço Promocional<span class="asterisk" >*</span>:</label> 
 	<%= f.text_field :preco_promocional, :class => 'long_text preco', :size => '10', :onkeypress => "onEnterLogin()" %> 
	</p>
	
	<p>
    <label>Catálogo<span class="asterisk" >*</span>:</label> 
	<%= collection_select :catalogo, :id, Catalogo.all, :id,:nome, options = {}, html_options={:class => "long_text"}%>
	
</p>
	
  <br/>
  <div class="actions">
    	 <%= submit_tag "Salvar", :class => "button negative", :onclick => "checkPreco();"  %> 
  <br/>
  </div>
  <br/>
<% end %>

app/views/produtos/edit.html.erb
<script>
$(document).ready(function(){
	$('#menu_buscarProduto').removeClass('selected');
	$('#menu_newProduto').removeClass('selected');
	$('#menu_produtos').removeClass('selected');
	$('#menu_newRevista').removeClass('selected');
	$('#menu_revistas').removeClass('selected');
	$('#menu_produtos').addClass('selected');

 });

</script>

<div class="grid_16">

    	<h1>
    	   <div class="title"><span class="title_icon"><img src="/assets/bullet1.gif" alt="" title="" /></span>Editar Produto</div>
    	</h1>


    	<div class="clear"></div>

    	<p></p>

    	<div class="formdiv">
            <fieldset class="login">
                <legend>Produto</legend>
    			<%= render 'form' %>
                <div>
    			</div>
            </fieldset>
    	</div>
    </div>

app/views/produtos/index.html.erb
<div class="title"><span class="title_icon"><img src="/assets/bullet1.gif" alt="" title="" /></span>Produtos</div>
<script>
$(document).ready(function(){
	$('#menu_buscarProduto').removeClass('selected');
	$('#menu_newProduto').removeClass('selected');
	$('#menu_produtos').removeClass('selected');
	$('#menu_newRevista').removeClass('selected');
	$('#menu_revistas').removeClass('selected');
	$('#menu_produtos').addClass('selected');

 });

 function confirmaDelete(){
	if(!confirm("Deseja remover esse produto?")){
		var e = window.event;
		e.cancelBubble = true;
		e.returnValue = false;

		if (e.stopPropagation) {
            e.stopPropagation();
            e.preventDefault();
			}
		}
	}
 
 
 
</script>



<div style="margin-left: 49px;color:green;font-family: calibri;font-size:12pt;">
<% flash.each do |name, msg| %>
   <b>   <%= content_tag :div, msg, :id => "flash_#{name}" %> </b>
	  <% end %>
</div>

<div style="margin-left: auto; margin-right:auto;">   

<br/>
<br/>
<br/>
<br/>
<div align="right"> 
<%= link_to 'Adicionar Produto', new_produto_path, :style => "width:150px;", :class => " adicionar big negative button" %>

    </div>
<table align="center">
  <tr>
    <th style="width:150px">Código</th>
    <th style="width:150px">Preco Promocional</th>
    <th style="width:150px">Preco Nominal</th>
	<th style="width:150px">Catálogo</th>
	<th style="width:150px"> Ações </th>
  </tr>

  
<% @produtos.each do |produto| %>
  <tr>
	<td> <%= produto.codigo_barras %> </td>
	<td><%= (number_to_currency(produto.preco_promocional, :unit => "R$ ", :precision => 2, :separator => ",", :delimiter => ".")) %> </td>
	<td> <%= (number_to_currency(produto.preco_nominal, :unit => "R$ ", :precision => 2, :separator => ",", :delimiter => ".")) %></td>
	<td> <%= produto.catalogo.nome %> </td>

    <td>
	<%= link_to (image_tag "buttons/button_remove.png", :size => "20x20", :style => "margin-right:10px;" ) ,{:controller => 'produtos', :action => 'destroy_produto', :id => produto.id}, :onclick => "confirmaDelete();"%>
	<%= link_to (image_tag "buttons/button_edit.png", :size => "20x20", :style => "margin-right:10px;" ) ,{:controller => 'produtos', :action => 'edit', :id => produto.id}%>
	<%= link_to (image_tag "buttons/glass.png",:size => "20x20" ) ,{:controller => 'produtos',:action => 'show', :id => produto.id}%>

  </tr>
<% end %>
</table>

<br />


</div>

app/views/produtos/new.html.erb
<script>
$(document).ready(function(){
	$('#menu_buscarProduto').removeClass('selected');
	$('#menu_newProduto').removeClass('selected');
	$('#menu_produtos').removeClass('selected');
	$('#menu_newRevista').removeClass('selected');
	$('#menu_revistas').removeClass('selected');
	$('#menu_newProduto').addClass('selected');

 });

</script>

<div class="grid_16">

	<% if Catalogo.all.count > 0 %>

    	<h1>
    	   <div class="title"><span class="title_icon"><img src="/assets/bullet1.gif" alt="" title="" /></span>Novo Produto</div>
    	</h1>
	
		<div style="margin-left: 49px;color:green;font-family: calibri;font-size:12pt;">
		<% flash.each do |name, msg| %>
   <b>   <%= content_tag :div, msg, :id => "flash_#{name}" %> </b>
		<% end %>
	</div>

    	<div class="clear"></div>

    	<p></p>

    	<div class="formdiv">
            <fieldset class="login">
                <legend>Produto</legend>
    			<%= render 'form' %>
                <div>
    			</div>
            </fieldset>
    	</div>
		
		
<% else %>
   <h1>
    	   <div class="title"><span class="title_icon"><img src="/assets/bullet1.gif" alt="" title="" /></span>Por favor cadastre um catálogo primeiro</div>
    	</h1>
		
		<div align="right"> 
<%= link_to 'Adicionar Catálogo', new_catalogo_path, :style => "width:150px;", :class => " adicionar big negative button" %>

    </div>
<% end %>
   </div>